version: "3.8"

services:
  db-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ninus
      MYSQL_USER: ninus-user
      MYSQL_PASSWORD: ninuspwd
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    volumes:
      - db-data:/mysql-data
    ports:
      - "3306:3306"
    container_name: db-mysql
    networks:
      - ninus-network

  db-client-adminer:
    depends_on:
      - db-mysql
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - ninus-network

  api-springboot:
    depends_on:
      - db-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/ninus-api
    container_name: api-springboot
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DOCKER_SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/ninus
      DOCKER_SPRING_DATASOURCE_USER: ninus-user
      DOCKER_SPRING_DATASOURCE_PASSWORD: ninuspwd
      DOCKER_SPRING_DATASOURCE_SHOW-SQL: true
      DOCKER_OPENAI_GPT_API_KEY: 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
      DOCKER_SPRING_PROFILES_ACTIVE: prod
    networks:
      - ninus-network

networks:
  ninus-network:

volumes:
  db-data: